CREATE CACHED TABLE DEVICE_STATE_HISTORY(
    ID VARCHAR(36) PRIMARY KEY,
    DEVICE_ID VARCHAR(36),
    NAME VARCHAR(255),
    VALUE VARCHAR(255),
    UNIT VARCHAR(50),
    DATE TIMESTAMP
);
CREATE INDEX DEVICE_STATE_HISTORY_DEVICEID_NAME_DATE_INDEX ON DEVICE_STATE_HISTORY (DEVICE_ID, NAME, DATE);
