/**
 * Copyright (c) 2021-2022 by the respective copyright holders.
 * All rights reserved.
 * <p>
 * This file is part of Parrot Home Automation Hub.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.parrotha.zwave.commands.timev1;

import com.parrotha.zwave.Command;

import com.parrotha.internal.utils.HexUtils;
import java.util.ArrayList;
import java.util.List;

/**
 * Note: This code is autogenerated, changes will be overwritten.
 */
public class DateReport extends Command {
    public String getCMD() {
        return "8A04";
    }

    private Integer year = 0;
    private Short month = 0;
    private Short day = 0;

    public Integer getYear() {
        return year;
    }

    public void setYear(Integer year) {
        this.year = year;
    }

    public Short getMonth() {
        return month;
    }

    public void setMonth(Short month) {
        this.month = month;
    }

    public Short getDay() {
        return day;
    }

    public void setDay(Short day) {
        this.day = day;
    }

    public List<Short> getPayload() {
        List<Short> retList = new ArrayList<>();
        retList.addAll(HexUtils.integerToShortList(year, 2));
        retList.add(month);
        retList.add(day);
        return retList;
    }

    public void setPayload(List<Short> payload) {
        if (payload == null) return;
        if (payload.size() > 2) {
            year = HexUtils.shortListToInteger(payload.subList(0, 2));
        }
        if (payload.size() > 2) {
            month = payload.get(2);
        }
        if (payload.size() > 3) {
            day = payload.get(3);
        }
    }

    @Override
    public String toString() {
        return "DateReport(" +
                "year: " + year +
                ", month: " + month +
                ", day: " + day +
                ')';
    }
}
