/**
 * Copyright (c) 2021-2023 by the respective copyright holders.
 * All rights reserved.
 * <p>
 * This file is part of Parrot Home Automation Hub.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.parrotha.zwave.commands.doorlockv1;

import com.parrotha.zwave.Command;

import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * Note: This code is autogenerated, changes will be overwritten.
 */
public class DoorLockOperationSet extends Command {
    public static final Short DOOR_LOCK_MODE_DOOR_UNSECURED = 0;
    public static final Short DOOR_LOCK_MODE_DOOR_UNSECURED_WITH_TIMEOUT = 1;
    public static final Short DOOR_LOCK_MODE_DOOR_UNSECURED_FOR_INSIDE_DOOR_HANDLES = 16;
    public static final Short DOOR_LOCK_MODE_DOOR_UNSECURED_FOR_INSIDE_DOOR_HANDLES_WITH_TIMEOUT = 17;
    public static final Short DOOR_LOCK_MODE_DOOR_UNSECURED_FOR_OUTSIDE_DOOR_HANDLES = 32;
    public static final Short DOOR_LOCK_MODE_DOOR_UNSECURED_FOR_OUTSIDE_DOOR_HANDLES_WITH_TIMEOUT = 33;
    public static final Short DOOR_LOCK_MODE_DOOR_SECURED = 255;

    public String getCMD() {
        return "6201";
    }

    private Short doorLockMode = 0;

    public Short getDoorLockMode() {
        return doorLockMode;
    }

    public void setDoorLockMode(Short doorLockMode) {
        this.doorLockMode = doorLockMode;
    }

    public List<Short> getPayload() {
        return Stream.of(doorLockMode).collect(Collectors.toList());
    }

    public void setPayload(List<Short> payload) {
        if (payload == null) return;
        if (payload.size() > 0) {
            doorLockMode = payload.get(0);
        }
    }

    @Override
    public String toString() {
        return "DoorLockOperationSet(" +
                "doorLockMode: " + doorLockMode +
                ')';
    }
}
