/**
 * Copyright (c) 2021 by the respective copyright holders.
 * All rights reserved.
 * <p>
 * This file is part of Parrot Home Automation Hub.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.parrotha.zwave.commands.basicv2;

import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * Note: This code is autogenerated, changes will be overwritten.
 */
public class BasicReport extends com.parrotha.zwave.commands.basicv1.BasicReport {
    public String getCMD() {
        return "2003";
    }

    private Short value = 0;
    private Short targetValue = 0;
    private Short duration = 0;

    public Short getValue() {
        return value;
    }

    public void setValue(Short value) {
        this.value = value;
    }

    public Short getTargetValue() {
        return targetValue;
    }

    public void setTargetValue(Short targetValue) {
        this.targetValue = targetValue;
    }

    public Short getDuration() {
        return duration;
    }

    public void setDuration(Short duration) {
        this.duration = duration;
    }

    public List<Short> getPayload() {
        return Stream.of(value, targetValue, duration).collect(Collectors.toList());
    }

    public void setPayload(List<Short> payload) {
        if (payload == null) return;
        if (payload.size() > 0) {
            value = payload.get(0);
        }
        if (payload.size() > 1) {
            targetValue = payload.get(1);
        }
        if (payload.size() > 2) {
            duration = payload.get(2);
        }
    }

    @Override
    public String toString() {
        return "BasicReport(" +
                "value: " + value +
                ", targetValue: " + targetValue +
                ", duration: " + duration +
                ')';
    }
}
