/**
 * Copyright (c) 2021 by the respective copyright holders.
 * All rights reserved.
 * <p>
 * This file is part of Parrot Home Automation Hub.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.parrotha.zwave.commands.manufacturerspecificv1;

import com.parrotha.zwave.Command;

import com.parrotha.internal.utils.HexUtils;
import java.util.ArrayList;
import java.util.List;

/**
 * Note: This code is autogenerated, changes will be overwritten.
 */
public class ManufacturerSpecificReport extends Command {
    public String getCMD() {
        return "7205";
    }

    private Integer manufacturerId = 0;
    private Integer productId = 0;
    private Integer productTypeId = 0;

    public Integer getManufacturerId() {
        return manufacturerId;
    }

    public void setManufacturerId(Integer manufacturerId) {
        this.manufacturerId = manufacturerId;
    }

    public Integer getProductId() {
        return productId;
    }

    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    public Integer getProductTypeId() {
        return productTypeId;
    }

    public void setProductTypeId(Integer productTypeId) {
        this.productTypeId = productTypeId;
    }

    public List<Short> getPayload() {
        List<Short> retList = new ArrayList<>();
        retList.addAll(HexUtils.integerToShortList(manufacturerId, 2));
        retList.addAll(HexUtils.integerToShortList(productId, 2));
        retList.addAll(HexUtils.integerToShortList(productTypeId, 2));
        return retList;
    }

    public void setPayload(List<Short> payload) {
        if (payload == null) return;
        if (payload.size() > 1) {
            manufacturerId = HexUtils.shortListToInteger(payload.subList(0, 2));
        }
        if (payload.size() > 3) {
            productId = HexUtils.shortListToInteger(payload.subList(2, 4));
        }
        if (payload.size() > 5) {
            productTypeId = HexUtils.shortListToInteger(payload.subList(4, 6));
        }
    }

    @Override
    public String toString() {
        return "ManufacturerSpecificReport(" +
                "manufacturerId: " + manufacturerId +
                ", productId: " + productId +
                ", productTypeId: " + productTypeId +
                ')';
    }
}
