/**
 * Copyright (c) 2021 by the respective copyright holders.
 * All rights reserved.
 * <p>
 * This file is part of Parrot Home Automation Hub.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.parrotha.zwave.commands.zipgatewayv1;

import com.parrotha.zwave.Command;

import com.parrotha.internal.utils.HexUtils;
import java.util.ArrayList;
import java.util.List;

/**
 * Note: This code is autogenerated, changes will be overwritten.
 */
public class UnsolicitedDestinationReport extends Command {
    public String getCMD() {
        return "5F0A";
    }

    private List<Short> ipv6Destination;
    private Integer destinationPort = 0;

    public List<Short> getIpv6Destination() {
        return ipv6Destination;
    }

    public void setIpv6Destination(List<Short> ipv6Destination) {
        this.ipv6Destination = ipv6Destination;
    }

    public Integer getDestinationPort() {
        return destinationPort;
    }

    public void setDestinationPort(Integer destinationPort) {
        this.destinationPort = destinationPort;
    }

    public List<Short> getPayload() {
        List<Short> retList = new ArrayList<>();
        retList.addAll(ipv6Destination);
        retList.addAll(HexUtils.integerToShortList(destinationPort, 2));
        return retList;
    }

    public void setPayload(List<Short> payload) {
        if (payload == null) return;
        if (payload.size() > 15) {
            ipv6Destination = payload.subList(0, 15);
        }
        if (payload.size() > 17) {
            destinationPort = HexUtils.shortListToInteger(payload.subList(16, 18));
        }
    }

    @Override
    public String toString() {
        return "UnsolicitedDestinationReport(" +
                "ipv6Destination: " + ipv6Destination +
                ", destinationPort: " + destinationPort +
                ')';
    }
}
