/**
 * Copyright (c) 2021-2022 by the respective copyright holders.
 * All rights reserved.
 * <p>
 * This file is part of Parrot Home Automation Hub.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.parrotha.zwave.commands.zipndv1;

import com.parrotha.zwave.Command;

import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * Note: This code is autogenerated, changes will be overwritten.
 */
public class ZipNodeAdvertisement extends Command {
    public String getCMD() {
        return "5801";
    }

    private Boolean local = false;
    private Short nodeId = 0;
    private List<Short> ipv6Address;
    private List<Short> homeId;

    public Boolean getLocal() {
        return local;
    }

    public void setLocal(Boolean local) {
        this.local = local;
    }

    public Short getNodeId() {
        return nodeId;
    }

    public void setNodeId(Short nodeId) {
        this.nodeId = nodeId;
    }

    public List<Short> getIpv6Address() {
        return ipv6Address;
    }

    public void setIpv6Address(List<Short> ipv6Address) {
        this.ipv6Address = ipv6Address;
    }

    public List<Short> getHomeId() {
        return homeId;
    }

    public void setHomeId(List<Short> homeId) {
        this.homeId = homeId;
    }

    public List<Short> getPayload() {
        Short data0 = (short) ((local == true ? (1 << 3) : 0));

        List<Short> retList = Stream.of(data0, nodeId).collect(Collectors.toList());
        retList.addAll(ipv6Address);
        retList.addAll(homeId);
        return retList;
    }

    public void setPayload(List<Short> payload) {
        if (payload == null) return;
        if (payload.size() > 0) {
            local = ((payload.get(0) >> 3) & 1) == 1;
        }
        if (payload.size() > 1) {
            nodeId = payload.get(1);
        }
        if (payload.size() > 18) {
            ipv6Address = payload.subList(2, 18);
        }
        if (payload.size() > 22) {
            homeId = payload.subList(19, 22);
        }
    }

    @Override
    public String toString() {
        return "ZipNodeAdvertisement(" +
                "local: " + local +
                ", nodeId: " + nodeId +
                ", ipv6Address: " + ipv6Address +
                ", homeId: " + homeId +
                ')';
    }
}
