/**
 * Copyright (c) 2021-2023 by the respective copyright holders.
 * All rights reserved.
 * <p>
 * This file is part of Parrot Home Automation Hub.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.parrotha.zwave.commandclasses;

import com.parrotha.zwave.internal.BeanUtils;

import java.lang.reflect.InvocationTargetException;
import java.util.Map;

/**
 * Note: This code is autogenerated, changes will be overwritten.
 */
public class AssociationV1 {
    public com.parrotha.zwave.commands.associationv1.AssociationSet associationSet() {
        return new com.parrotha.zwave.commands.associationv1.AssociationSet();
    }

    public com.parrotha.zwave.commands.associationv1.AssociationSet associationSet(Map values) throws InvocationTargetException, IllegalAccessException {
        com.parrotha.zwave.commands.associationv1.AssociationSet cmd = new com.parrotha.zwave.commands.associationv1.AssociationSet();
        BeanUtils.populate(cmd, values);
        return cmd;
    }

    public com.parrotha.zwave.commands.associationv1.AssociationGet associationGet() {
        return new com.parrotha.zwave.commands.associationv1.AssociationGet();
    }

    public com.parrotha.zwave.commands.associationv1.AssociationGet associationGet(Map values) throws InvocationTargetException, IllegalAccessException {
        com.parrotha.zwave.commands.associationv1.AssociationGet cmd = new com.parrotha.zwave.commands.associationv1.AssociationGet();
        BeanUtils.populate(cmd, values);
        return cmd;
    }

    public com.parrotha.zwave.commands.associationv1.AssociationReport associationReport() {
        return new com.parrotha.zwave.commands.associationv1.AssociationReport();
    }

    public com.parrotha.zwave.commands.associationv1.AssociationReport associationReport(Map values) throws InvocationTargetException, IllegalAccessException {
        com.parrotha.zwave.commands.associationv1.AssociationReport cmd = new com.parrotha.zwave.commands.associationv1.AssociationReport();
        BeanUtils.populate(cmd, values);
        return cmd;
    }

    public com.parrotha.zwave.commands.associationv1.AssociationRemove associationRemove() {
        return new com.parrotha.zwave.commands.associationv1.AssociationRemove();
    }

    public com.parrotha.zwave.commands.associationv1.AssociationRemove associationRemove(Map values) throws InvocationTargetException, IllegalAccessException {
        com.parrotha.zwave.commands.associationv1.AssociationRemove cmd = new com.parrotha.zwave.commands.associationv1.AssociationRemove();
        BeanUtils.populate(cmd, values);
        return cmd;
    }

    public com.parrotha.zwave.commands.associationv1.AssociationGroupingsGet associationGroupingsGet() {
        return new com.parrotha.zwave.commands.associationv1.AssociationGroupingsGet();
    }

    public com.parrotha.zwave.commands.associationv1.AssociationGroupingsGet associationGroupingsGet(Map values) throws InvocationTargetException, IllegalAccessException {
        com.parrotha.zwave.commands.associationv1.AssociationGroupingsGet cmd = new com.parrotha.zwave.commands.associationv1.AssociationGroupingsGet();
        BeanUtils.populate(cmd, values);
        return cmd;
    }

    public com.parrotha.zwave.commands.associationv1.AssociationGroupingsReport associationGroupingsReport() {
        return new com.parrotha.zwave.commands.associationv1.AssociationGroupingsReport();
    }

    public com.parrotha.zwave.commands.associationv1.AssociationGroupingsReport associationGroupingsReport(Map values) throws InvocationTargetException, IllegalAccessException {
        com.parrotha.zwave.commands.associationv1.AssociationGroupingsReport cmd = new com.parrotha.zwave.commands.associationv1.AssociationGroupingsReport();
        BeanUtils.populate(cmd, values);
        return cmd;
    }

}
