/**
 * Copyright (c) 2021 by the respective copyright holders.
 * All rights reserved.
 * <p>
 * This file is part of Parrot Home Automation Hub.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.parrotha.zwave.commandclasses;

import org.apache.commons.beanutils.BeanUtils;

import java.lang.reflect.InvocationTargetException;
import java.util.Map;

/**
 * Note: This code is autogenerated, changes will be overwritten.
 */
public class ConfigurationV2 {
    public com.parrotha.zwave.commands.configurationv2.ConfigurationSet configurationSet() {
        return new com.parrotha.zwave.commands.configurationv2.ConfigurationSet();
    }

    public com.parrotha.zwave.commands.configurationv2.ConfigurationSet configurationSet(Map values) throws InvocationTargetException, IllegalAccessException {
        com.parrotha.zwave.commands.configurationv2.ConfigurationSet cmd = new com.parrotha.zwave.commands.configurationv2.ConfigurationSet();
        BeanUtils.populate(cmd, values);
        return cmd;
    }

    public com.parrotha.zwave.commands.configurationv2.ConfigurationGet configurationGet() {
        return new com.parrotha.zwave.commands.configurationv2.ConfigurationGet();
    }

    public com.parrotha.zwave.commands.configurationv2.ConfigurationGet configurationGet(Map values) throws InvocationTargetException, IllegalAccessException {
        com.parrotha.zwave.commands.configurationv2.ConfigurationGet cmd = new com.parrotha.zwave.commands.configurationv2.ConfigurationGet();
        BeanUtils.populate(cmd, values);
        return cmd;
    }

    public com.parrotha.zwave.commands.configurationv2.ConfigurationReport configurationReport() {
        return new com.parrotha.zwave.commands.configurationv2.ConfigurationReport();
    }

    public com.parrotha.zwave.commands.configurationv2.ConfigurationReport configurationReport(Map values) throws InvocationTargetException, IllegalAccessException {
        com.parrotha.zwave.commands.configurationv2.ConfigurationReport cmd = new com.parrotha.zwave.commands.configurationv2.ConfigurationReport();
        BeanUtils.populate(cmd, values);
        return cmd;
    }

}
