/**
 * Copyright (c) 2021 by the respective copyright holders.
 * All rights reserved.
 * <p>
 * This file is part of Parrot Home Automation Hub.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.parrotha.zwave.commandclasses;

import org.apache.commons.beanutils.BeanUtils;

import java.lang.reflect.InvocationTargetException;
import java.util.Map;

/**
 * Note: This code is autogenerated, changes will be overwritten.
 */
public class ManufacturerSpecificV2 {
    public com.parrotha.zwave.commands.manufacturerspecificv2.ManufacturerSpecificGet manufacturerSpecificGet() {
        return new com.parrotha.zwave.commands.manufacturerspecificv2.ManufacturerSpecificGet();
    }

    public com.parrotha.zwave.commands.manufacturerspecificv2.ManufacturerSpecificGet manufacturerSpecificGet(Map values) throws InvocationTargetException, IllegalAccessException {
        com.parrotha.zwave.commands.manufacturerspecificv2.ManufacturerSpecificGet cmd = new com.parrotha.zwave.commands.manufacturerspecificv2.ManufacturerSpecificGet();
        BeanUtils.populate(cmd, values);
        return cmd;
    }

    public com.parrotha.zwave.commands.manufacturerspecificv2.ManufacturerSpecificReport manufacturerSpecificReport() {
        return new com.parrotha.zwave.commands.manufacturerspecificv2.ManufacturerSpecificReport();
    }

    public com.parrotha.zwave.commands.manufacturerspecificv2.ManufacturerSpecificReport manufacturerSpecificReport(Map values) throws InvocationTargetException, IllegalAccessException {
        com.parrotha.zwave.commands.manufacturerspecificv2.ManufacturerSpecificReport cmd = new com.parrotha.zwave.commands.manufacturerspecificv2.ManufacturerSpecificReport();
        BeanUtils.populate(cmd, values);
        return cmd;
    }

    public com.parrotha.zwave.commands.manufacturerspecificv2.DeviceSpecificGet deviceSpecificGet() {
        return new com.parrotha.zwave.commands.manufacturerspecificv2.DeviceSpecificGet();
    }

    public com.parrotha.zwave.commands.manufacturerspecificv2.DeviceSpecificGet deviceSpecificGet(Map values) throws InvocationTargetException, IllegalAccessException {
        com.parrotha.zwave.commands.manufacturerspecificv2.DeviceSpecificGet cmd = new com.parrotha.zwave.commands.manufacturerspecificv2.DeviceSpecificGet();
        BeanUtils.populate(cmd, values);
        return cmd;
    }

    public com.parrotha.zwave.commands.manufacturerspecificv2.DeviceSpecificReport deviceSpecificReport() {
        return new com.parrotha.zwave.commands.manufacturerspecificv2.DeviceSpecificReport();
    }

    public com.parrotha.zwave.commands.manufacturerspecificv2.DeviceSpecificReport deviceSpecificReport(Map values) throws InvocationTargetException, IllegalAccessException {
        com.parrotha.zwave.commands.manufacturerspecificv2.DeviceSpecificReport cmd = new com.parrotha.zwave.commands.manufacturerspecificv2.DeviceSpecificReport();
        BeanUtils.populate(cmd, values);
        return cmd;
    }

}
