/**
 * Copyright (c) 2021-2022 by the respective copyright holders.
 * All rights reserved.
 * <p>
 * This file is part of Parrot Home Automation Hub.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.parrotha.zwave.commandclasses;

import com.parrotha.zwave.internal.BeanUtils;

import java.lang.reflect.InvocationTargetException;
import java.util.Map;

/**
 * Note: This code is autogenerated, changes will be overwritten.
 */
public class ThermostatFanModeV1 {
    public com.parrotha.zwave.commands.thermostatfanmodev1.ThermostatFanModeSet thermostatFanModeSet() {
        return new com.parrotha.zwave.commands.thermostatfanmodev1.ThermostatFanModeSet();
    }

    public com.parrotha.zwave.commands.thermostatfanmodev1.ThermostatFanModeSet thermostatFanModeSet(Map values) throws InvocationTargetException, IllegalAccessException {
        com.parrotha.zwave.commands.thermostatfanmodev1.ThermostatFanModeSet cmd = new com.parrotha.zwave.commands.thermostatfanmodev1.ThermostatFanModeSet();
        BeanUtils.populate(cmd, values);
        return cmd;
    }

    public com.parrotha.zwave.commands.thermostatfanmodev1.ThermostatFanModeGet thermostatFanModeGet() {
        return new com.parrotha.zwave.commands.thermostatfanmodev1.ThermostatFanModeGet();
    }

    public com.parrotha.zwave.commands.thermostatfanmodev1.ThermostatFanModeGet thermostatFanModeGet(Map values) throws InvocationTargetException, IllegalAccessException {
        com.parrotha.zwave.commands.thermostatfanmodev1.ThermostatFanModeGet cmd = new com.parrotha.zwave.commands.thermostatfanmodev1.ThermostatFanModeGet();
        BeanUtils.populate(cmd, values);
        return cmd;
    }

    public com.parrotha.zwave.commands.thermostatfanmodev1.ThermostatFanModeReport thermostatFanModeReport() {
        return new com.parrotha.zwave.commands.thermostatfanmodev1.ThermostatFanModeReport();
    }

    public com.parrotha.zwave.commands.thermostatfanmodev1.ThermostatFanModeReport thermostatFanModeReport(Map values) throws InvocationTargetException, IllegalAccessException {
        com.parrotha.zwave.commands.thermostatfanmodev1.ThermostatFanModeReport cmd = new com.parrotha.zwave.commands.thermostatfanmodev1.ThermostatFanModeReport();
        BeanUtils.populate(cmd, values);
        return cmd;
    }

    public com.parrotha.zwave.commands.thermostatfanmodev1.ThermostatFanModeSupportedGet thermostatFanModeSupportedGet() {
        return new com.parrotha.zwave.commands.thermostatfanmodev1.ThermostatFanModeSupportedGet();
    }

    public com.parrotha.zwave.commands.thermostatfanmodev1.ThermostatFanModeSupportedGet thermostatFanModeSupportedGet(Map values) throws InvocationTargetException, IllegalAccessException {
        com.parrotha.zwave.commands.thermostatfanmodev1.ThermostatFanModeSupportedGet cmd = new com.parrotha.zwave.commands.thermostatfanmodev1.ThermostatFanModeSupportedGet();
        BeanUtils.populate(cmd, values);
        return cmd;
    }

    public com.parrotha.zwave.commands.thermostatfanmodev1.ThermostatFanModeSupportedReport thermostatFanModeSupportedReport() {
        return new com.parrotha.zwave.commands.thermostatfanmodev1.ThermostatFanModeSupportedReport();
    }

    public com.parrotha.zwave.commands.thermostatfanmodev1.ThermostatFanModeSupportedReport thermostatFanModeSupportedReport(Map values) throws InvocationTargetException, IllegalAccessException {
        com.parrotha.zwave.commands.thermostatfanmodev1.ThermostatFanModeSupportedReport cmd = new com.parrotha.zwave.commands.thermostatfanmodev1.ThermostatFanModeSupportedReport();
        BeanUtils.populate(cmd, values);
        return cmd;
    }

}
