/**
 * Copyright (c) 2021 by the respective copyright holders.
 * All rights reserved.
 * <p>
 * This file is part of Parrot Home Automation Hub.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.parrotha.zwave.commandclasses;

import org.apache.commons.beanutils.BeanUtils;

import java.lang.reflect.InvocationTargetException;
import java.util.Map;

/**
 * Note: This code is autogenerated, changes will be overwritten.
 */
public class TimeV1 {
    public com.parrotha.zwave.commands.timev1.TimeGet timeGet() {
        return new com.parrotha.zwave.commands.timev1.TimeGet();
    }

    public com.parrotha.zwave.commands.timev1.TimeGet timeGet(Map values) throws InvocationTargetException, IllegalAccessException {
        com.parrotha.zwave.commands.timev1.TimeGet cmd = new com.parrotha.zwave.commands.timev1.TimeGet();
        BeanUtils.populate(cmd, values);
        return cmd;
    }

    public com.parrotha.zwave.commands.timev1.TimeReport timeReport() {
        return new com.parrotha.zwave.commands.timev1.TimeReport();
    }

    public com.parrotha.zwave.commands.timev1.TimeReport timeReport(Map values) throws InvocationTargetException, IllegalAccessException {
        com.parrotha.zwave.commands.timev1.TimeReport cmd = new com.parrotha.zwave.commands.timev1.TimeReport();
        BeanUtils.populate(cmd, values);
        return cmd;
    }

    public com.parrotha.zwave.commands.timev1.DateGet dateGet() {
        return new com.parrotha.zwave.commands.timev1.DateGet();
    }

    public com.parrotha.zwave.commands.timev1.DateGet dateGet(Map values) throws InvocationTargetException, IllegalAccessException {
        com.parrotha.zwave.commands.timev1.DateGet cmd = new com.parrotha.zwave.commands.timev1.DateGet();
        BeanUtils.populate(cmd, values);
        return cmd;
    }

    public com.parrotha.zwave.commands.timev1.DateReport dateReport() {
        return new com.parrotha.zwave.commands.timev1.DateReport();
    }

    public com.parrotha.zwave.commands.timev1.DateReport dateReport(Map values) throws InvocationTargetException, IllegalAccessException {
        com.parrotha.zwave.commands.timev1.DateReport cmd = new com.parrotha.zwave.commands.timev1.DateReport();
        BeanUtils.populate(cmd, values);
        return cmd;
    }

}
