/**
 * Copyright (c) 2021 by the respective copyright holders.
 * All rights reserved.
 * <p>
 * This file is part of Parrot Home Automation Hub.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.parrotha.zwave.commands.switchbinaryv2;

import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * Note: This code is autogenerated, changes will be overwritten.
 */
public class SwitchBinarySet extends com.parrotha.zwave.commands.switchbinaryv1.SwitchBinarySet {
    public String getCMD() {
        return "2501";
    }

    private Short switchValue = 0;
    private Short duration = 0;

    public Short getSwitchValue() {
        return switchValue;
    }

    public void setSwitchValue(Short switchValue) {
        this.switchValue = switchValue;
    }

    public Short getDuration() {
        return duration;
    }

    public void setDuration(Short duration) {
        this.duration = duration;
    }

    public List<Short> getPayload() {
        return Stream.of(switchValue, duration).collect(Collectors.toList());
    }

    public void setPayload(List<Short> payload) {
        if (payload == null) return;
        if (payload.size() > 0) {
            switchValue = payload.get(0);
        }
        if (payload.size() > 1) {
            duration = payload.get(1);
        }
    }

    @Override
    public String toString() {
        return "SwitchBinarySet(" +
                "switchValue: " + switchValue +
                ", duration: " + duration +
                ')';
    }
}
